### ISSUE TITLE
ma ze kapara?

### ISSUE THREAD

**Issue by Kronenberg** [shirbr510/capara#1]
🐙

**Comment by shirbr510** [comment]
Kapara (Mostly written as Capara)'s official definition is "a Hebrew word meaning often used as a pet name by Mizrahi(eastern) and Sephardi(Spanish origin) Jews."
if you'd like to use it on a person, usually, it's referred to "a friend / someone I like/ general person that I'm speaking too."
in judaism, it also acts as a synonym to forgiveness or redemption.

reference: https://www.urbandictionary.com/define.php?term=kapara

let me know if it's a thorough enough definition 😄

**Comment by Kronenberg** [comment]
Thx! aval ze 🐙 octopus. you misunderstood me :(

**Comment by shirbr510** [comment]
tagid tamnoon, capara! 🐙
