### ISSUE TITLE
npm -C capara not working

### ISSUE THREAD

**Issue by Kronenberg** [shirbr510/capara#2]
- My node version is: v_____322_$%%%_capara
- I have this error: 
```
VM122:1 Uncaught ReferenceError: capara is not defined
-     at <anonymous> please go eat falafel
```

**Comment by shirbr510** [comment]
this repository is about creating the pseudo language and not the explicit implementations per language.

once we will have the spec properly defined we will create the implementation per language.

you are welcome to help us with capara-js when time comes if you'd like to 😄
